In [11]:
import svd_solve as svd
import numpy as np

A = np.array([[10, 2, 3],
              [4, 5, 6],
              [7, 8, 9],])

U, Sigma, V_T, cond_num, A_inv = svd.svd_solve(A)
A_reconstructed = U @ Sigma @ V_T

# NumPy's built-in SVD function for comparison
np_U, np_SingularValues, np_V_T = np.linalg.svd(A)

# Construct the Sigma matrix using NumPy's SVD
np_Sigma = np.zeros_like(A, dtype=float)
min_dim = min(A.shape[0], A.shape[1])
np.fill_diagonal(np_Sigma[:min_dim, :min_dim], np_SingularValues)

# Reconstructing the matrix A using NumPy's SVD components
np_A_reconstructed = np_U @ np_Sigma @ np_V_T

# Print the matrices for comparison
print("Custom U:")
print(U)

print("\nNumPy U:")
print(np_U)

# Compare V_T matrices
print("\nCustom V_T:")
print(V_T)

print("\nNumPy V_T:")
print(np_V_T)

# Compare Sigma matrices
print("\nCustom Sigma:")
print(Sigma)

print("\nNumPy Sigma:")
print(np_Sigma)

# Compare the reconstructed matrix A
print("\nCustom Reconstructed Matrix (U @ Sigma @ V_T):")
print(A_reconstructed)

print("\nNumPy Reconstructed Matrix (U @ Sigma @ V_T):")
print(np_A_reconstructed)

Custom U:
[[ 0.49323762  0.86819544 -0.05434456]
 [ 0.460219   -0.31345194 -0.8306301 ]
 [ 0.73818367 -0.38468761  0.55416632]]

NumPy U:
[[-0.49323762  0.86819544 -0.05434456]
 [-0.460219   -0.31345194 -0.8306301 ]
 [-0.73818367 -0.38468761  0.55416632]]

Custom V_T:
[[ 0.6423315   0.49453207  0.58553248]
 [ 0.76435664 -0.46945622 -0.44200655]
 [ 0.05629545  0.73147036 -0.67954538]]

NumPy V_T:
[[-0.6423315  -0.49453207 -0.58553248]
 [ 0.76435664 -0.46945622 -0.44200655]
 [ 0.05629545  0.73147036 -0.67954538]]

Custom Sigma:
[[18.58936996  0.          0.        ]
 [ 0.          6.19518838  0.        ]
 [ 0.          0.          0.23444694]]

NumPy Sigma:
[[18.58936996  0.          0.        ]
 [ 0.          6.19518838  0.        ]
 [ 0.          0.          0.23444694]]

Custom Reconstructed Matrix (U @ Sigma @ V_T):
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]

NumPy Reconstructed Matrix (U @ Sigma @ V_T):
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [12]:
# Insert the updated comparison code here
print("Custom SVD solver condition number and inverse matrix:")
print("Condition Number:", cond_num)
print("Inverse of A:")
print(A_inv)

print("\nNumPy condition number and inverse matrix:")
print("Condition Number:", np.linalg.cond(A))
print("Inverse of A:")
print(np.linalg.inv(A))

Custom SVD solver condition number and inverse matrix:
Condition Number: 79.29030599962555
Inverse of A:
[[ 0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -2.55555556  1.77777778]
 [ 0.11111111  2.44444444 -1.55555556]]

NumPy condition number and inverse matrix:
Condition Number: 79.2903059996245
Inverse of A:
[[ 0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -2.55555556  1.77777778]
 [ 0.11111111  2.44444444 -1.55555556]]
